version: '3'

services:
  # Database
  db13:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - db_data13:/var/lib/mysql
    networks:
      - c13network

  phpmyadmin:
    depends_on:
      - db13
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8050:80'
    environment:
      PMA_HOST: db13
      MYSQL_ROOT_PASSWORD: password
    networks:
      - c13network
  
  wordpress:
    depends_on:
      - db13
    image: wordpress:latest
    ports:
      - '8000:80'
    restart: always
    volumes: ['./:/var/www/html']
    environment:
      WORDPRESS_DB_HOST: db13:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    networks:
      - c13network

networks:
  c13network:

volumes:
  db_data13: